// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogInOutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logInOut() {
    driver.get("https://www.answers.com/");
    driver.manage().window().setSize(new Dimension(1600, 900));
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div/div[4]/div[3]/span/button")).click();
    driver.findElement(By.cssSelector(".col-span-6")).click();
    driver.findElement(By.xpath("//input[@id=\'email-input\']")).sendKeys("pabape1117@galcake.com");
    driver.findElement(By.xpath("//input[@id=\'outlined-adornment-password\']")).sendKeys("xxx666999");
    driver.findElement(By.xpath("//form[@id=\'loginUser\']/button")).click();
    driver.findElement(By.xpath("//img[@alt=\'User Avatar\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/div/div/div[4]/div[3]/span/div/div/div/button[2]/a"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div/div[4]/div[3]/span/div/div/div/button[3]/a/span")).click();
  }
}
