// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchQuestionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchQuestions() {
    driver.get("https://www.answers.com/");
    driver.manage().window().setSize(new Dimension(1600, 900));
    driver.findElement(By.xpath("//input[@id=\'search-input\']")).click();
    driver.findElement(By.xpath("//input[@id=\'search-input\']")).sendKeys("what\'s");
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section/div[2]/div/div[2]/div/a[2]/div/span")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'best-answer\']/div/div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//img[@alt=\'answersLogoWhite\']")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section")).click();
    driver.findElement(By.xpath("//input[@id=\'search-input\']")).click();
    driver.findElement(By.xpath("//input[@id=\'search-input\']")).sendKeys("how to");
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section/div[2]/div/div[2]/div/a[3]/div/h2")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'best-answer\']/div/div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//img[@alt=\'answersLogoWhite\']")).click();
  }
}
